version: '3.1'
services:
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
  mysql:
    image: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: example
    ports: 
      - 3306:3306
  mongo:
    image: mongo
    restart: always
    ports:
        - 27017:27017
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
  redis:
    image: redis
    ports:
      - 6379:6379 